### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Aeronkle** [ToThangGTVT/todo-web-forme#7]
Hello i want to learn how to make a anonymous chat on facebook messenger, can you teach me for it I'm from the Philippines, thank you for responds

**Comment by ToThangGTVT** [comment]
Hello, I developed app chatbot before. It use webhook with backend is java spring boot.
You can understand webhook is technology, FB will call REST API to that server when user send message on your FB Page.
So your todo is define api to facebook call to.
All event of FB you can check here: https://developers.facebook.com/docs/messenger-platform
This is repo anonymous chat on facebook messenger that I developed: https://github.com/ToThangGTVT/chatbot . Code of that repo realy complex because I make it when I am fresher.
Good luck my friend^^

**Comment by ToThangGTVT** [comment]
> Hello i want to learn how to make a anonymous chat on facebook messenger, can you teach me for it I'm from the Philippines, thank you for responds

Hello, I developed app chatbot before. It use webhook with backend is java spring boot.
You can understand webhook is technology, FB will call REST API to that server when user send message on your FB Page.
So your todo is define api to facebook call to.
All event of FB you can check here: https://developers.facebook.com/docs/messenger-platform
This is repo anonymous chat on facebook messenger that I developed: https://github.com/ToThangGTVT/chatbot . Code of that repo realy complex because I make it when I am fresher.
Good luck my friend^^

**Comment by Aeronkle** [comment]
thank you, how to deploy it?  can i deploy it using heroku or I'm creating a website like 000webhost or profreehost? 😊

**Comment by ToThangGTVT** [comment]
You can deloy it on heroku, and database is mongodb.
It is all free

**Comment by ToThangGTVT** [comment]
I just edited my repo

**Comment by Aeronkle** [comment]
thank you ❤, i am still learning how to code but i have i little knowledge in javascript and html only like for about 50%😊

**Comment by Aeronkle** [comment]
hello, i have a source code here on fb-chatbot that other developer gave me, Can you fix the error, because i don't know how to fix it....  Programming language is Only Node.js.... Thank you, i wait your response..

**Comment by Aeronkle** [comment]
Hello can you help me, i have a fb chatbot source code written in Node.js that the other developer shared me, but i don't know how to fix the error.  Can you help me to fix the error and the Package-lock.json is old... I can give you my another unpublished facebook pages with over 3,000 followers and likes and completely manageable and no violation or restrictions... Just help me to this,  thank you for responds😊

**Comment by ToThangGTVT** [comment]
You can delete file package-lock and run `npm i`. Sorry, now i don't have time fix bug for you. Or you can paste log on this issue, so I can help you easier

**Comment by Aeronkle** [comment]
ok, great! I deploy the code using heroku and when i open the "View Log" and here's it says:



2022-05-29T16:11:31.255007+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-05-29T16:11:31.255007+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-05-29T16:11:31.255007+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2022-05-29T16:11:31.255008+00:00 app[web.1]:     at require (node:internal/modules/cjs/helpers:102:18)
2022-05-29T16:11:31.255008+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:4:21)
2022-05-29T16:11:31.255008+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-05-29T16:11:31.378429+00:00 heroku[web.1]: Process exited with status 1
2022-05-29T16:11:31.425261+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-29T16:11:44.795689+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=bot-fb-nbc.herokuapp.com request_id=d7e018b7-8d13-4c4d-a51e-76634b6f7b28 fwd="81.90.189.54" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T16:11:46.347169+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=bot-fb-nbc.herokuapp.com request_id=a6000012-490e-4d75-b971-77d79d8989fa fwd="81.90.189.54" dyno= connect= service= status=503 bytes= protocol=https

**Comment by Aeronkle** [comment]
And then i try to deploy it using vercel.com and here is the Deployment Logs:


Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings



And then when i open the "Visit Site" here is the link to see it: https://nearbychat-fnyxogmw5-aeronkle.vercel.app/       ---- here is the viewpage:

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cdg1::sz7hf-1653841688398-37166863b763

If you are a visitor, contact the website owner or try again later.
If you are the owner, learn how to fix the error and check the logs.

**Comment by Aeronkle** [comment]
Please help me with this🙏, my node.js code is for fb bot that allow user to make a stranger to stranger conversation...  I'm frustrated with more than a week ago for fixing the errors on the code, please help me to this to fix this..  i ask help of  the owner of the code but he didn't not help me... please help me to fix it, i can give you my another unpublished facebook pages with 3,000 followers and likes,  thank you very much 😄🙏..

**Comment by Aeronkle** [comment]
By the way, how to connect or use mongodb? 😅

**Comment by ToThangGTVT** [comment]
According log, i see file app.js (line 4), you can run it on local and dubug. With mongo, you have to create account at mongodb.com after use connect string, which mongo.com supply to connect.

**Comment by ToThangGTVT** [comment]
I think you was not connect to mongodb, so app nodejs was crash.

**Comment by Aeronkle** [comment]
you're right.. I'm not connected on mongodb, i think connecting to mongodb is the solution, but i don't know how to connect or use it😅, can you teach me.....
-
-

How to find this: MongoUri: '#'
-
-

Here is my pair.js:

const FB_CONST = require('../../const');
const MongoClient = require('mongodb').MongoClient;
require('dotenv').config();
const MongoUri = process.env.MONGO_URI;
const MongoDbName =
    process.env.MONGODB_DBNAME || require("parse-mongo-url")(MongoUri).dbName;
module.exports = {
    randomPartner: function randomPartner(senderId) {
        return new Promise(resolve => {
            MongoClient.connect(MongoUri, { useNewUrlParser: true }).then(conn => {
              return conn
                .db(MongoDbName)
                .collection("Users")
                .findOne({
                    _id: {$ne: senderId},
                    partnerId: null,
                    status: 0
                })
                .then(res => {
                  conn.close();
                  resolve(res);
                })
                .catch(err => console.log(err));
            });
          });
    }
}

-
-
-

And here is my user.js:

const FB_CONST = require('../../const');
const MongoClient = require('mongodb').MongoClient;
require('dotenv').config();
const MongoUri = process.env.MONGO_URI;
const MongoDbName =
  process.env.MONGODB_DBNAME || require("parse-mongo-url")(MongoUri).dbName;
module.exports = {
  createUser: function createUser(userData, idPartner) {
    return new Promise(async resolve => {
      MongoClient.connect(MongoUri, { useNewUrlParser: true }).then(conn => {
        let json = {
          _id: userData.id,
          first_name: userData.first_name,
          last_name: userData.last_name,
          profile_pic: userData.profile_pic,
          status: 0, //0 not, 1 paired
          partnerId: null,
          timerequest: null,
          gender: userData.gender,
          favoriteGender: "any",
          partnerInfo: idPartner ? [{
            id: idPartner,
            time: {startDate: new Date(), endDate: null}
          }] : null
        };
        return conn
          .db(MongoDbName)
          .collection("Users")
          .insertOne(json)
          .then(() => {
            resolve(json);
            conn.close();
          })
          .catch(err => console.log(err));
      });
    });
  },

  getUser: function getUser(senderId) {
    return new Promise(resolve => {
      MongoClient.connect(MongoUri, { useNewUrlParser: true }).then(conn => {
        return conn
          .db(MongoDbName)
          .collection("Users")
          .findOne({
            _id: senderId,
          })
          .then(res => {
            conn.close();
            resolve(res);
          })
          .catch(err => console.log(err));
      });
    });
  },

  updateUser: function updateUser(senderId, data) {
    return new Promise(resolve => {
      MongoClient.connect(MongoUri, { useNewUrlParser: true }).then(conn => {
        return conn
          .db(MongoDbName)
          .collection("Users")
          .updateOne(
            {
              _id: senderId
            },
            {
              $set: data
            }
          )
          .then(res => {
            conn.close();
            resolve(res);
          })
          .catch(err => console.log(err));
      });
    });
  }
}

**Comment by Aeronkle** [comment]
you're right.. I'm not connected on mongodb, i think connecting to mongodb is the solution, but i don't know how to connect or use it😅, can you teach me.....
-
-

How to find this: MongoUri: '#' -in mongodb
How to find: 'MongoDbName'
-
-

Here is my pair.js:

const FB_CONST = require('../../const');
const MongoClient = require('mongodb').MongoClient;
require('dotenv').config();
const MongoUri = process.env.MONGO_URI;
const MongoDbName =
    process.env.MONGODB_DBNAME || require("parse-mongo-url")(MongoUri).dbName;
module.exports = {
    randomPartner: function randomPartner(senderId) {
        return new Promise(resolve => {
            MongoClient.connect(MongoUri, { useNewUrlParser: true }).then(conn => {
              return conn
                .db(MongoDbName)
                .collection("Users")
                .findOne({
                    _id: {$ne: senderId},
                    partnerId: null,
                    status: 0
                })
                .then(res => {
                  conn.close();
                  resolve(res);
                })
                .catch(err => console.log(err));
            });
          });
    }
}

-
-
-

**Comment by Aeronkle** [comment]
by the another way, what env is required in your fb chatbot anonymous chat code. and what files should i change, i know rest api now....

**Comment by ToThangGTVT** [comment]
![image](https://user-images.githubusercontent.com/33534455/171002053-2e28bcb9-cc5a-47c5-945d-0f1ce5ef8f3f.png)
String connection of mongodb, it here

**Comment by ToThangGTVT** [comment]
![image](https://user-images.githubusercontent.com/33534455/171002268-51124422-f2ab-4620-bb1a-58c0c0fd929c.png)
String connection of mongodb, it here.

**Comment by ToThangGTVT** [comment]
Env of project, you can read all project to know. 
You can create app at https://developers.facebook.com, it here have document of messenger platform and also have sample project demo

**Comment by ToThangGTVT** [comment]
As I know, You enter that connection string in Studio3T and create database, name of database is `const MongoDbName = ...`

**Comment by Aeronkle** [comment]
Ok,  thank you😊, I'll create an account for studio3t, i was able to solve app.js at line 4 that you said, but i still seen "Application Error" when I'm opening the app.. 

Here's is my latest application log on heroku:

2022-05-30T15:45:35.419133+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-05-30T15:45:35.419134+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-05-30T15:45:35.419135+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-05-30T15:45:35.419136+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-05-30T15:45:35.419136+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
2022-05-30T15:45:35.419136+00:00 app[web.1]:     at node:internal/main/run_main_module:17:47
2022-05-30T15:45:35.573702+00:00 heroku[web.1]: Process exited with status 1
2022-05-30T15:45:35.628204+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-30T15:45:36.751708+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=bot-fb-nbc.herokuapp.com request_id=1cdffcea-67a8-4257-83b7-4abb2b98c6ae fwd="81.90.189.54" dyno= connect= service= status=503 bytes= protocol=https
2022-05-30T15:45:40.680901+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=bot-fb-nbc.herokuapp.com request_id=b5603791-93c3-4d23-ad86-9d1ed11dc660 fwd="81.90.189.54" dyno= connect= service= status=503 bytes= protocol=https

**Comment by Aeronkle** [comment]
Oh, it seems i need to download it😅, do you have studio3t ? i can give you my connection string😄

**Comment by ToThangGTVT** [comment]
Studio 3t is free tool, you can download it
